In [1]:
import pandas as pd
import os

In [2]:
## Set up parameters

## Genome assembly
genome='/nfs/team205/is10/resources/ucsc_genomes/hg38.fa'

## Output directory
outdir = '/lustre/scratch126/cellgen/team205/is10/fibroblasts/bulk_cytokines/cistarget/'
os.makedirs(outdir, exist_ok=True)

In [3]:
## Read peaks to be used as background for analysis:
peaks = pd.read_csv('/lustre/scratch126/cellgen/team205/sk29/matthias_fb/bulk_ATACseq_pipeline/tables/peak_table_all_PCA_loadings_matched.csv')

In [4]:
peaks

,seqnames,start,end,width,strand,annotation,geneChr,geneStart,geneEnd,geneLength,...,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,atac_peak
0,chr1,41457,41706,250,*,Distal Intergenic,1,34554,36081,1528,...,-0.000218,0.000058,0.001293,-0.000572,-0.005215,0.001466,0.002297,0.001722,-0.000018,NaN
1,chr1,41844,42454,611,*,Distal Intergenic,1,34554,36081,1528,...,0.003238,0.001186,-0.000434,0.002903,-0.002480,0.000492,0.000058,0.001749,-0.002107,NaN
2,chr1,46484,46643,160,*,Distal Intergenic,1,34554,36081,1528,...,-0.001927,0.000680,-0.002111,-0.002085,-0.001672,0.000305,0.002181,0.003427,0.000431,NaN
3,chr1,47458,47787,330,*,Distal Intergenic,1,34554,36081,1528,...,0.001765,-0.001260,0.000677,-0.001215,0.002317,0.000459,0.004452,-0.000025,0.001623,NaN
4,chr1,56157,56477,321,*,Distal Intergenic,1,65419,71585,6167,...,0.001766,0.002055,0.001975,-0.003827,-0.002879,0.002733,-0.001658,0.000824,0.001074,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
334845,chrY,24270821,24270977,157,*,Distal Intergenic,24,24209567,24215581,6015,...,0.000484,-0.004116,0.001355,-0.003388,-0.000105,-0.001377,-0.002405,-0.000864,0.000583,NaN
334846,chrY,24271380,24271691,312,*,Distal Intergenic,24,24209567,24215581,6015,...,0.002053,-0.000959,0.000523,0.001065,-0.001394,0.002850,0.000024,-0.002099,-0.001052,NaN
334847,chrY,24368003,24368602,600,*,Distal Intergenic,24,24485332,24486463,1132,...,0.000261,-0.000502,0.002325,0.000269,0.001189,-0.001753,0.001466,-0.001661,-0.001990,NaN
334848,chrY,25301540,25302124,585,*,Distal Intergenic,24,25182277,25213389,31113,...,0.001629,-0.000410,-0.003819,0.000374,0.000060,-0.000084,-0.001369,0.000147,0.000106,NaN
334849,chrY,25398454,25398765,312,*,Distal Intergenic,24,25454561,25460572,6012,...,0.002922,-0.000456,0.000430,-0.000514,-0.001021,-0.001565,0.002035,0.001442,0.000431,NaN

In [5]:
## Extracting coordinates
peak_coord = peaks[['seqnames', 'start', 'end']]

In [6]:
## Adding the peak's name
peak_coord['name'] = peaks['seqnames'] + ':' + peaks['start'].astype(str) + '-' + peaks['end'].astype(str)

/tmp/ipykernel_152032/581865842.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  peak_coord['name'] = peaks['seqnames'] + ':' + peaks['start'].astype(str) + '-' + peaks['end'].astype(str)

In [7]:
peak_coord

       seqnames     start       end                    name
0          chr1     41457     41706        chr1:41457-41706
1          chr1     41844     42454        chr1:41844-42454
2          chr1     46484     46643        chr1:46484-46643
3          chr1     47458     47787        chr1:47458-47787
4          chr1     56157     56477        chr1:56157-56477
...         ...       ...       ...                     ...
334845     chrY  24270821  24270977  chrY:24270821-24270977
334846     chrY  24271380  24271691  chrY:24271380-24271691
334847     chrY  24368003  24368602  chrY:24368003-24368602
334848     chrY  25301540  25302124  chrY:25301540-25302124
334849     chrY  25398454  25398765  chrY:25398454-25398765

[334850 rows x 4 columns]

In [8]:
## Export into bed format
peak_coord.to_csv((outdir + 'all_peaks.bed'), sep='\t', index=False, header=False)

In [9]:
## And convert to fasta
os.system(('bedtools getfasta -fi ' + genome + ' -bed ' + outdir + 'all_peaks.bed > ' + outdir + 'all_peaks.fa'))

0